apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    development: client-web
spec:
  replicas: 3
  selector:
    matchLabels:
      development: client-pod
  template:
    metadata:
      labels:
        development: client-pod
    spec:
      containers:
        - name: client-webapp
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
