apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip
  labels:
    app: postgres-cluster-ip

spec:
  type: ClusterIP
  selector:
    development: postgres
  ports:
    - port: 5432
      targetPort: 5432