apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  labels:
    app: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      development: postgres
  template:
    metadata:
      name: postgres-app
      labels:
        development: postgres
    spec:
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: persistent-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD


