apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    development: server-web
spec:
  replicas: 3
  selector:
    matchLabels:
      development: server-app
  template:
    metadata:
      labels:
        development: server-app
    spec:
      containers:
        - name: web-server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
